# Generated by Django 4.2.1 on 2023-05-29 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id_number", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=64)),
                ("middle_name", models.CharField(blank=True, max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.IntegerField()),
                ("date_of_birth", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_date", models.DateField()),
                ("salary_value", models.IntegerField()),
                ("update_date", models.DateField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salaries",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PositionAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employees.employee",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="positions.position",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "position")},
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="positions",
            field=models.ManyToManyField(
                through="employees.PositionAssignment", to="positions.position"
            ),
        ),
    ]
