# Generated by Django 4.2.1 on 2023-06-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
