# Generated by Django 4.2.1 on 2023-06-22 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
